// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dzoqrevbxnwpshxteiut.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR6b3FyZXZieG53cHNoeHRlaXV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4NjA4NzAsImV4cCI6MjA3MDQzNjg3MH0.vc4sfluV994b09Uysu_vuj0DjrB-32ybeZMpGfMInxI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});